### PR TITLE
Vertx 3

### PR DESCRIPTION
**Pull request by RichardHightower**
This looks like it is working. Tests seem to pass. More testing needs to be done.
https://github.com/advantageous/qbit/issues/407

### CODE REVIEW

**Comment by RichardHightower** [comment]
@sailorgeoffrey made some good progress on adding Vertx3 support.
@fadihub 
@revelfire

**Comment by RichardHightower** [comment]
@sailorgeoffrey @fadihub @revelfire Please review this code.

**Comment by sailorgeoffrey** [comment]
I'm not sure I like making a new vertx3 project if all the other projects stop using the vertx one.  This just makes a pile of dead code.  If someone needs the old vert.x they can use the old qbit, because the new qbit won't work with the old vertx

**Comment by RichardHightower** [comment]
@sailorgeoffrey 
Here is some of my thought process.
https://github.com/advantageous/qbit/wiki/%5BDoc%5D-QBit-and-Vertx3-:-Best-of-both-worlds-for-Microservices

I plan on getting rid of the vertx 2 support.

But we need to burn in the vertx 3 support first.

**Comment by RichardHightower** [comment]
@sailorgeoffrey 
I also was not sure if I was going to support vertx 2 anymore.
I was putting short. I can merge the changes into vertx and get rid of vertx3 lib.

**Comment by RichardHightower** [comment]
@sailorgeoffrey I just merged the changes. Now there is only vertx, which happens to be vertx3.

**Comment by RichardHightower** [comment]
@sailorgeoffrey 
@revelfire 
Anyone want to give this the thumbs up?

**Comment by RichardHightower** [comment]
Hello I am a pull request. I am all dressed up and no one gives me a thumbs up. Rick will vote thumbs up on me by tomorrow if me, the lowly pull request, does not get any love.

**Pull request merged**
