### PR TITLE
Pass contextual data map when creating an HttpRequest in post and put methods

### PR DESCRIPTION
**Pull request by bbyk**

### CODE REVIEW

**Comment by RichardHightower** [comment]
What is the memory cost of creating an empty HashMap for every request?
Is there anyway that we can lazy create it when needed?

**Comment by bbyk** [comment]
@RichardHightower I pass `data` in because it actually has some content in it. This is the stuff where, say, a vertx filter handles authentication and passes some user object via the map

**Comment by RichardHightower** [comment]
I understand, but I want to make it so we don't init the map until someone adds something so for the cases where we don't need the map we don't create one. I accepted the patch btw. I just might make the map creation lazy at some point.

**Comment by bbyk** [comment]
Gotcha

**Pull request merged**
