### PR TITLE
Qbit 2

### PR DESCRIPTION
**Pull request by RichardHightower**
Moving to Reakt 4

### CODE REVIEW

**Comment by RichardHightower** [comment]
@sailorgeoffrey @jasond44

**Comment by bwzhang2011** [comment]
@RichardHightower, any update with such issue ? as qbit seemed not release any stable version after 1.10 since June. just care about whether it would be progressed or not.

**Comment by RichardHightower** [comment]
We are due for another release.

**Comment by bwzhang2011** [comment]
@RichardHightower, thanks for feedback and looking forward to such release soon, best wishes.

**Pull request merged**
